# Generated by Django 5.0.3 on 2024-03-26 09:35

import app_06.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_06", "0002_alter_post_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(validators=[app_06.models.validate_age]),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, validators=[app_06.models.validate_bad_words]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    app_06.models.validate_email,
                    django.core.validators.EmailValidator(
                        message="Enter a valid email"
                    ),
                ],
            ),
        ),
    ]
