# Generated by Django 5.0.3 on 2024-03-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_06", "0003_alter_user_age_alter_user_bio_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
